version: "2"

linters:
  default: none
  enable:
    - copyloopvar
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    goconst:
      ignore-tests: true
      min-occurrences: 10
    lll:
      line-length: 140
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - lll
          - errcheck
      - path: test/
        linters:
          - lll
          - errcheck

formatters:
  enable:
    - gofmt
    - goimports
