apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mint4v.fullname" . }}
  labels:
    {{- include "mint4v.labels" . | nindent 4 }}
data:
  config.hcl: |
    {{- .Values.config | nindent 4 }}
