{{- if .Values.vaultCA }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mint4v.vaultCASecretName" . }}
  labels:
    {{- include "mint4v.labels" . | nindent 4 }}
stringData:
  ca.crt: |
    {{- .Values.vaultCA | nindent 4 }}
{{- end }}
{{- if .Values.targetCA }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mint4v.targetCASecretName" . }}
  labels:
    {{- include "mint4v.labels" . | nindent 4 }}
stringData:
  ca.crt: |
    {{- .Values.targetCA | nindent 4 }}
{{- end }}
{{- if .Values.credentials }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mint4v.credentialsSecretName" . }}
  labels:
    {{- include "mint4v.labels" . | nindent 4 }}
stringData:
  credentials.json: |
    {{- .Values.credentials | nindent 4 }}
{{- end }}
