{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mint4v.serviceAccountName" . }}
  labels:
    {{- include "mint4v.labels" . | nindent 4 }}
{{- end }}
